Fix issue when using AUTO_INVOICING_REUSE_DRAFT and with (subscriptio…
killbill/killbill pull request #1360
Opened 2020-09-16 23:48 UTC by sbrossie

…n) dates in the past.

The scenario is one where we have AUTO_INVOICING_DRAFT/AUTO_INVOICING_REUSE_DRAFT set on the account
and we create some subscriptions in the past.

There will be an initial bus event for the start date creating the invoice and adding the first RECURRING period (from test example: 8/7 -> 9/1)
Then, a notification be picked up immediately for the next RECURRING period as its effective date is in the past (9/1 -> 10/1)

Unfortunately prior the fix the targetDate which is computed as the max(event date, all invoices targetDate) is wrong because targetDate from (resused) invoice
was not updated.

This fix will now update the targetDate associated with the ongoing (reused) invoice and therefore avoid all the REPAIR we were seeing.

2020-09-17 04:43 UTC, pierre requested changes

2020-09-17 04:43 UTC, pierre commented on beatrix/src/test/java/org/killbill/billing/beatrix/integration/TestIntegrationBase.java
> +            log.info(": {} queue(s) with more notification(s) to process", nbNotifications);
Nit: the comment is incorrect, it's not the number of queues, but the number of notifications.

2020-09-17 04:43 UTC, pierre commented on invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
> +                                    (invoiceOnDisk.getTargetDate() == null || invoiceOnDisk.getTargetDate().compareTo(invoiceModelDao.getTargetDate()) != 0))) {
I'm wondering if you need to explicitly check that `invoiceOnDisk.getTargetDate().compareTo(invoiceModelDao.getTargetDate()) < 0`, to make sure we never go back in time.

Could you trigger a target date bill run in the past in your test, before committing the final invoice, and verify the resulting target date?

2020-09-17 04:43 UTC, pierre commented on invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
> +                        } else if (invoiceOnDisk.getStatus() != invoiceModelDao.getStatus() || /* Update if status is different */
`Update if status is different` -> I'm a tad nervous about this, as there is nothing preventing the code now to do other transitions, such as `COMMITTED` -> `VOID`.

2020-09-17 16:42 UTC, sbrossie commented
@pierre Agree with all your comments. See https://github.com/killbill/killbill/pull/1360/commits/7514c6fe36b4f39482eb07c3b03cd51b716ce376

2020-09-17 17:51 UTC, pierre commented on invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
> +                            final InvoiceStatus newStatus = (InvoiceStatus.COMMITTED == invoiceModelDao.getStatus() && InvoiceStatus.COMMITTED != invoiceOnDisk.getStatus()) ? InvoiceStatus.COMMITTED
`InvoiceStatus.COMMITTED != invoiceOnDisk.getStatus()` -> `invoiceOnDisk.getStatus() == InvoiceStatus.DRAFT` to be strictly backward compatible (e.g. prevent transition from `VOID` to `COMMITTED`).

2020-09-17 17:51 UTC, pierre commented on invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
> +import java.util.Objects;
Fancy!

2020-09-17 17:51 UTC, pierre commented on invoice/src/main/java/org/killbill/billing/invoice/dao/DefaultInvoiceDao.java
> +                            if (newStatus != invoiceOnDisk.getStatus() || !Objects.equals(newTargetDate, invoiceOnDisk.getTargetDate())) {
Does that work with dates (it uses `compareTo`)?

2020-09-18 09:30 UTC, pierre approved these changes

2020-09-18 09:30 UTC, merged