apply Catalog API Blocks and Limit data type from Double to BigDecimal
killbill/killbill pull request #1590
Opened 2022-02-07 12:45 UTC by xsalefter

based on comment on this issue: https://github.com/killbill/killbill/issues/1469#issuecomment-1028580177 .

Related Pull Request in API: https://github.com/killbill/killbill-api/pull/84

2022-02-09 00:13 UTC, sbrossie requested changes
Left a couple of comments to address, and also running the test locally, I get a test failure: ```/testing-mysql-server17086277404870518227/mysql.sock databaseb008b64d
2022-02-08T19:14:26.581+0000 [main] ERROR org.killbill.billing.GuicyKillbillTestSuiteWithEmbeddedDB - **********************************************************************************************
[ERROR] Tests run: 111, Failures: 1, Errors: 0, Skipped: 40, Time elapsed: 17.941 s <<< FAILURE! - in TestSuite
[ERROR] org.killbill.billing.catalog.dao.TestCatalogOverrideDao.testGetOverriddenPlanPhasesWithUsageOverrides  Time elapsed: 0.056 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [1.0]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:617)
	at org.killbill.billing.catalog.dao.TestCatalogOverrideDao.testGetOverriddenPlanPhasesWithUsageOverrides(TestCatalogOverrideDao.java:152)
```

2022-02-09 00:13 UTC, sbrossie commented on catalog/src/main/java/org/killbill/billing/catalog/DefaultLimit.java
> +     *   will fails. It is because in some XML (test file), max and or min value is not set, and lead to null value.
We need to change this field and come up with a fix for the test to pass - perhaps as simple as updating the xml fail with a default value ?

2022-02-09 00:13 UTC, sbrossie commented on catalog/src/main/java/org/killbill/billing/catalog/DefaultPrice.java
> +        // super.initialize(catalog);
Why are we removing this `initialize` call?

2022-02-09 00:13 UTC, sbrossie commented on catalog/src/main/java/org/killbill/billing/catalog/DefaultTieredBlock.java
> +        temp = Double.doubleToLongBits(max.doubleValue());
No more `double`, needs to be changed.

2022-02-09 00:13 UTC, sbrossie commented on catalog/src/main/java/org/killbill/billing/catalog/dao/CatalogOverrideBlockDefinitionModelDao.java
> +    private double bsize; // FIXME-1469 Catalog: Should we change this as well
Yes, should be changed.

2022-02-09 00:13 UTC, sbrossie commented on invoice/src/main/java/org/killbill/billing/invoice/usage/ContiguousIntervalCapacityUsageInArrear.java
> +                // if (tierLimit.getMax() != (double) -1 && ro.getAmount().doubleValue() > tierLimit.getMax()) {
Extra comment?

2022-02-09 22:36 UTC, sbrossie commented
@xsalefter I just merged your `killbill-api` PR, and as a result a snapshot was created. Could you update the value of  [killbill-api.version](https://github.com/xsalefter/killbill/blob/fix_1469-catalog_api/pom.xml#L63) to `0.54.0-0010563-SNAPSHOT` - this will allow `ci` jobs to work once your code is in place?

2022-02-14 11:08 UTC, xsalefter commented on catalog/src/main/resources/org/killbill/billing/catalog/migration/V20220208000000__change_usage_and_catalog_attrs_type.sql
> +alter table rolled_up_usage modify amount decimal(17, 9) not null;
This one was typo hahahah.. anyway, fixed.

2022-02-14 16:50 UTC, merged