https://github.com/killbill/killbill/issues/1944
killbill/killbill pull request #2032
Opened 2024-07-02 19:03 UTC by KBbitsP

2024-07-05 06:01 UTC, reshmabidikar reviewed
Would it be possible to add some beatrix tests to confirm that the fix works?

2024-07-05 06:01 UTC, reshmabidikar commented on catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java
> +        if (input == null||!input.iterator().hasNext()) {
Nit: Missing space after `input == null`

2024-07-05 06:01 UTC, reshmabidikar commented on catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java
> +        if (input == null||!input.iterator().hasNext()) {
Nit: Missing space after input == null

2024-07-08 18:13 UTC, sbrossie reviewed
What about [here](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java#L227): Isn't it another use case where the input could be null that is not handled properly?

2024-07-17 00:45 UTC, sbrossie requested changes

2024-07-17 00:45 UTC, sbrossie commented on catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java
> +        if (input == null) {
This method is called [here](https://github.com/killbill/killbill/blob/master/catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java#L109C16-L109C27), and if you follow the code it seems like we would get an NPE... 

Can you return a `Collections.emptyList()` instead?

2024-07-17 00:45 UTC, sbrossie commented on catalog/src/main/java/org/killbill/billing/catalog/plugin/StandaloneCatalogMapper.java
> +            return null;
Same remark as before. Can you return a `Collections.emptyList()` instead?

2025-01-21 08:34 UTC, reshmabidikar commented
Closing this PR, will open a separate PR with the fix.

2025-01-21 08:34 UTC, closed without merging